atomicfi/atomic-transact-react-native

.github/pull_request_template.md, android/build.gradle, android/src/main/java/com/atomicfi/transactreactnative/TransactReactNativeModule.kt, atomicfi-transact-react-native.podspec, package.json, src/android.tsx
https://linear.app/atomicbuilt/issue/PAY-703/update-rn-sdk-with-paylink-support
=> feat: pay-link release

android/build.gradle
https://linear.app/atomicbuilt/issue/DD-1108
=> chore(android): transact 3.5.2

atomicfi-transact-react-native.podspec, package.json
https://linear.app/atomicbuilt/issue/MUP-16
=> chore: bump ios and rn version

android/build.gradle
https://linear.app/atomicbuilt/issue/DD-1133
=> chore(android): transact 3.5.3

.github/workflows/publish.yml, package.json
https://linear.app/atomicbuilt/issue/DD-1150/automate-rn-deployment
=> feat: add automated deployment to npm

src/constants.tsx
https://linear.app/atomicbuilt/issue/PAY-765/add-switch-to-rn-package
=> feat: add switch to product constants

package.json
https://linear.app/atomicbuilt/issue/PAY-765/add-switch-to-rn-package
=> chore: release version 3.6.0

package.json
https://linear.app/atomicbuilt/issue/PAY-767/typings-missing-from-rn-sdk
=> fix: add typings

package.json
https://linear.app/atomicbuilt/issue/PAY-767/typings-missing-from-rn-sdk
=> chore: release 3.6.1

android/build.gradle
https://linear.app/atomicbuilt/issue/DD-1244/
=> chore(android): transact 3.5.4

package.json
https://linear.app/atomicbuilt/issue/PAY-806/upgrade-rn-sdk-to-use-ios-sdk-version-364
=> chore: bump version to 3.6.3

package.json
https://linear.app/atomicbuilt/issue/DD-1277/you-can-just-swipe-away-the-ios-sdk
=> chore: release 3.6.4

package.json
https://linear.app/atomicbuilt/issue/PAY-927/have-transact-control-when-ios-background-process-is-created
=> chore: release 3.6.5

src/index.tsx
https://linear.app/atomicbuilt/issue/DD-1329/add-navigationoptions-typing-to-react-native-project
=> chore: add type definitions for navigation options into theme

package.json
Please replace this with a link to your Linear task.
=> chore: release 3.6.6

package.json
https://linear.app/atomicbuilt/issue/SUB-34/detect-when-action-was-launched
=> chore: release 3.7.0

src/ios.tsx
https://linear.app/atomicbuilt/issue/SUB-34/detect-when-action-was-launched
=> fix: this is a type

package.json
https://linear.app/atomicbuilt/issue/SUB-34/detect-when-action-was-launched
=> chore: release 3.7.1

android/build.gradle
https://linear.app/atomicbuilt/issue/DD-1399
=> chore(android): transact 3.5.5

package.json
https://linear.app/atomicbuilt/issue/DD-1406
=> chore: release 3.7.2

package.json
https://linear.app/atomicbuilt/issue/MGMT-48/allow-transact-webview-to-be-shown-hidden-via-transact
=> chore: release 3.7.3

package.json
https://linear.app/atomicbuilt/issue/MGMT-54
=> chore: release 3.7.4

atomicfi-transact-react-native.podspec, example/ios/Podfile.lock, example/src/App.tsx, ios/TransactReactNative.swift, src/index.tsx, src/ios.tsx
https://linear.app/atomicbuilt/issue/MGMT-66/add-onclose-callback-to-presentaction-in-ios-sdk
=> feat(present-action): update callback events

package.json
https://linear.app/atomicbuilt/issue/MGMT-66/add-onclose-callback-to-presentaction-in-ios-sdk
=> chore: release 3.8.0

package.json
https://linear.app/atomicbuilt/issue/MGMT-168/upgrade-muppet
=> chore: release 3.8.1

package.json
https://linear.app/atomicbuilt/issue/MGMT-206/bump-rn-sdk-to-394
=> chore: release 3.8.2

android/build.gradle, android/src/main/java/com/atomicfi/transactreactnative/TransactReactNativeModule.kt, example/ios/Podfile.lock, example/src/App.tsx, src/android.tsx, src/index.tsx
https://linear.app/atomicbuilt/issue/MGMT-309/react-native-sdk
https://github.com/user-attachments/assets/0af32e1e-e732-4c38-a47d-ed3a9a69a070
=> feat: add android support for presentAction

package.json
https://linear.app/atomicbuilt/issue/MGMT-309/react-native-sdk
=> chore: bump version to 3.9.0

package.json
https://linear.app/atomicbuilt/issue/DD-1604
=> chore: release 3.9.1

atomicfi-transact-react-native.podspec, example/ios/Podfile.lock
https://linear.app/atomicbuilt/issue/MGMT-561/update-react-native-sdk-with-latest-ios-skd
=> chore: update ios-sdk to 3.9.20

package.json
Please replace this with a link to your Linear task.
=> chore: release 3.9.2

atomicfi-transact-react-native.podspec, example/ios/Podfile.lock, package.json
https://linear.app/atomicbuilt/issue/MGMT-565/update-ios-sdk-in-react-native-sdk
=> chore: update iOS to 3.9.23

src/index.tsx
https://linear.app/atomicbuilt/issue/PAY-1173/customer-param-in-rn-sdk
=> feat: add customer option to atomic config

atomicfi-transact-react-native.podspec, example/ios/Podfile.lock, package.json
https://linear.app/atomicbuilt/issue/MGMT-587/update-and-release-react-native-sdk-with-mgmt-558-fix
=> chore: update with 3.10.0 ios AtomicSDK

android/build.gradle, atomicfi-transact-react-native.podspec, package.json
https://linear.app/atomicbuilt/issue/SDK-28/update-ios-sdk-version-in-react-native-sdk-for-chime
https://linear.app/atomicbuilt/issue/SDK-26/upgrade-atomic-transact-android-dep-in-rn-sdk
=> chore: update native sdk versions

package.json
https://linear.app/atomicbuilt/issue/SDK-41/bump-rn-android-version-to-3113
=> chore: bump version to 3.12.3

example/screens/PresentActionScreen.tsx, example/screens/TransactScreen.tsx, ios/TransactReactNative.m, ios/TransactReactNative.swift, src/constants.tsx, src/index.tsx, src/ios.tsx
https://linear.app/atomicbuilt/issue/SDK-56/add-presentationstyleios-option-to-rn-sdk
=> feat: add support for presentationStyleIOS
